spring:
  application:
    name: moviesv2
  jpa:
    hibernate:
      ddl-auto: none
    database: ${POSTGRES_DATABASE}
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
